import type { NextPage } from 'next'
import Head from 'next/head'
import Label from '../components/Label'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import { MetaMaskInpageProvider } from '@metamask/providers'
import { ethers } from 'ethers'

declare global {
  interface Window {
    ethereum: ethers.providers.ExternalProvider
  }
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nutrition Label</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <Navbar />
      <Label />
      <div className={styles.background}></div>
      <div className={styles.gradient}></div>
    </div>
  )
}

export default Home
