import type { NextPage } from 'next'
import Head from 'next/head'
import Label from '../components/Label'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nutrition Label</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Label />
      <div className={styles.background}></div>
      <div className={styles.gradient}></div>
    </div>
  )
}

export default Home
